# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ecb767988253486633689922c18261d5dfae043e8b17f1ee1720adaeb49d34e741be8b2302ad3135156220b8d0d9988de3988efad9bb5b40281786df65f90f7

test:
  secret_key_base: 596c93ba5ea6f9a531d4c0f06a70018e389bb08b0a216f4a3deff2a0b3cdd5868f28e0ab356d49ccd76a5d45d230b9600e259ff557d344159c31314c1f429f4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
